# Suggested repository labels to match .github/release.yml categories
# Use GitHub CLI to apply: see README section "Release Notes & Labels"

labels:
  - name: breaking-change
    color: FF0000
    description: Breaking change requiring user action

  - name: ui
    color: 8A2BE2
    description: User interface changes

  - name: ux
    color: 9370DB
    description: User experience improvements

  - name: layout
    color: 1E90FF
    description: Layout/template changes

  - name: routes
    color: 4169E1
    description: Routing changes

  - name: auth
    color: 6495ED
    description: Authentication and authorization

  - name: security
    color: 228B22
    description: Security-related changes

  - name: filters
    color: 2E8B57
    description: Filters and middleware

  - name: admin
    color: 20B2AA
    description: Admin area changes

  - name: settings
    color: 3CB371
    description: Settings and configuration UI

  - name: blog
    color: F4A460
    description: Blog feature changes

  - name: build
    color: 708090
    description: Build system changes

  - name: tooling
    color: 778899
    description: Tooling and DX improvements

  - name: tests
    color: 6A5ACD
    description: Test suite changes

  - name: test
    color: 7B68EE
    description: Test-related minor change

  - name: docs
    color: 00CED1
    description: Documentation updates

  - name: documentation
    color: 40E0D0
    description: Documentation improvements

  - name: dependencies
    color: A52A2A
    description: Dependency updates

  - name: deps
    color: B22222
    description: Dependency bumps/cleanup

  - name: chore
    color: D3D3D3
    description: Maintenance chores and housekeeping

  - name: maintenance
    color: C0C0C0
    description: Maintenance tasks

  - name: skip-changelog
    color: 000000
    description: Exclude from autogenerated release notes

  - name: ci
    color: 2F4F4F
    description: Continuous integration

  - name: wip
    color: FFD700
    description: Work in progress